### PR TITLE
Retar tool to fix sunodo build locale issue

### PR DESCRIPTION
**Pull request by tuler**
This installs `locales` package and set `en_US.UTF-8` as default locale.

### CODE REVIEW

**Comment by endersonmaia** [comment]
@tuler I think we need at least a patch changests for the `sunodo/sdk` package.

**Comment by endersonmaia** [comment]
I get this:

```
❯ ../bin/run.js build
[+] Building 2.1s (18/18) FINISHED                                                                                                                                                                                                                           
 => [internal] load .dockerignore                                                                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 760B                                                                                                                                                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                                                                                                                                                            0.6s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc                                                                                                                       0.0s
 => [internal] load metadata for docker.io/sunodo/machine-emulator-tools:0.11.0-ubuntu22.04                                                                                                                                                             1.4s
 => [internal] load metadata for docker.io/cartesi/python:3.10-slim-jammy                                                                                                                                                                               1.4s
 => [auth] cartesi/python:pull token for registry-1.docker.io                                                                                                                                                                                           0.0s
 => [auth] sunodo/machine-emulator-tools:pull token for registry-1.docker.io                                                                                                                                                                            0.0s
 => [stage-0 1/7] FROM docker.io/cartesi/python:3.10-slim-jammy@sha256:a60d99fcd98d563e633bd06d28e2be94c7da45f335691edd9cbf3a0830694638                                                                                                                 0.0s
 => [internal] load build context                                                                                                                                                                                                                       0.0s
 => => transferring context: 64B                                                                                                                                                                                                                        0.0s
 => FROM docker.io/sunodo/machine-emulator-tools:0.11.0-ubuntu22.04@sha256:589165eab2d067c158c68eed5046f912e54679fc03f2dc0dc4a3b8c3917bdd50                                                                                                             0.0s
 => CACHED [stage-0 2/7] RUN <<EOF (apt-get update...)                                                                                                                                                                                                  0.0s
 => CACHED [stage-0 3/7] COPY --from=sunodo/machine-emulator-tools:0.11.0-ubuntu22.04 / /                                                                                                                                                               0.0s
 => CACHED [stage-0 4/7] WORKDIR /opt/cartesi/dapp                                                                                                                                                                                                      0.0s
 => CACHED [stage-0 5/7] COPY ./requirements.txt .                                                                                                                                                                                                      0.0s
 => CACHED [stage-0 6/7] RUN <<EOF (pip install -r requirements.txt --no-cache...)                                                                                                                                                                      0.0s
 => CACHED [stage-0 7/7] COPY ./dapp.py .                                                                                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                                                                                                 0.0s
 => => writing image sha256:6887713de273941d2d2af477fb8b893e0b16f5ce75aba36d70fcc793b468b181                                                                                                                                                            0.0s
genext2fs: archive_read_next_header(): Linkname can't be converted from UTF-8 to current locale.
    Error: Command failed with exit code 1: docker container run --rm --env USER=endersonmaia --env GROUP=container-group-1000 --env UID=1000 --env GID=1000 --volume /home/endersonmaia/Development/sunodo/sunodo/apps/cli/my-python-dapp/.sunodo:/mnt 
    sunodo/sdk:devel genext2fs --tarball /mnt/image.tar --block-size 4096 --faketime -r +2560 /mnt/image.ext2
```

**Comment by endersonmaia** [comment]
It worked here, squash the fixups so I can approve.

**Review by endersonmaia — APPROVED** [review]

**Comment by tuler** [comment]
I think the SDK change and the CLI change should be in separate PRs and with a release between them, no?

because the CLI change only works with the upcoming release of sdk (0.1.0)

**Comment by endersonmaia** [comment]
> I think the SDK change and the CLI change should be in separate PRs and with a release between them, no?
> 
> because the CLI change only works with the upcoming release of sdk (0.1.0)

I'm not sure. Won't it work if we release both together right after the merge?

**Comment by tuler** [comment]
No, unless I change [here](https://github.com/sunodo/sunodo/blob/0908b7c63e6629f26adfa84a9ef5df236db40b0a/apps/cli/src/commands/build.ts#L29) and/or in the template.

**Comment by tuler** [comment]
Split this PR into this and https://github.com/sunodo/sunodo/pull/71
Release this SDK first, then do a CLI release

**Review by endersonmaia — APPROVED** [review]

**Pull request merged**
