### PR TITLE
Authority indexing

### PR DESCRIPTION
**Pull request by tuler**
This PR adds a [subsquid](https://www.subsquid.io) for indexing the authorities created by the AuthorityFactory
It's meant to be deployed to [subsquid aquarium](https://app.subsquid.io)

### CODE REVIEW

**Comment by tuler** [comment]
I have a problem with the deployment of this subsquid to aquarium using `sqd deploy`
Aquarium doesn't support yet monorepos or yarn. It expects a `package-lock.json` file to build a docker image from the source code.

`sqd deploy` creates a `.tar.gz` of the source code of the current directory, upload to aquarium. Then a build happens on their server by unpacking the code and running a docker build with the Dockerfile described [here](https://docs.subsquid.io/deploy-squid/self-hosting/), which executes a `npm ci`.

My problem is that this subsquid project is part of a yarn monorepo, so there is no package-lock.json. I tried the following approaches, none worked well:

1. run `npm install` from the `subsquid` package. This creates a `package-lock.json` in the root of the monorepo. Then copy that file to `packages/subsquid`. 

2. Run `yarn turbe prune --scope=@sunodo/subsquid`. This creates a `out/` directory with only the `subsquid` project and its dependencies (`@sunodo/wagmi-plugin-hardhat-deploy`). Then follow step 1.

Maybe @brunomenezes has an idea?

**Comment by brunomenezes** [comment]
> Maybe @brunomenezes has an idea?

I have [issue#32](https://github.com/cartesi/explorer/issues/32) to experiment with Subsquid, but I did not start on it yet. What is the error you are getting? I'll probably have the same problem since Explorer uses turborepo + yarn.

**Comment by tuler** [comment]
Solved the problem of subsquid not supporting yarn monorepos by moving the project "outside" of our monorepo, in a directory not managed by the monorepo, and removing the dependency to the `@sunodo/wagmi-plugin-hardhat-deploy` package for now.

**Comment by tuler** [comment]
@SocketSecurity ignore es5-ext@0.10.62

**Review by endersonmaia — APPROVED** [review]

**Pull request merged**
