### PR TITLE
IPFS Car download

### PR DESCRIPTION
**Pull request by tuler**
Utility and library to download CAR from IPFS and save to local filesystem.
More information in the README.md file.

The implementation uses typescript async generators to traverse files of a CAR, then download each CAR and report progress to the user by yielding intermediate information (progress).

The communication with the IPFS network is provided by [helia](https://helia.io).

### CODE REVIEW

**Comment by tuler** [comment]
> * @SocketSecurity ignore npm/node-datachannel@0.5.3

@SocketSecurity ignore npm/node-datachannel@0.5.3

**Comment by tuler** [comment]
@SocketSecurity ignore npm/node-datachannel@0.5.3

**Comment by endersonmaia** [comment]
I can build but tests failed.

```
❯ cd packages/car-download
❯ yarn test
yarn run v1.22.21
$ vitest

 DEV  v1.2.2 /home/endersonmaia/Development/sunodo/sunodo/packages/car-download

include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think we should also add a test step to the CI.

**Comment by tuler** [comment]
> I can build but tests failed.

I didn't write tests yet. I think it can come in the near future.

> I think we should also add a test step to the CI.

Agreed, once we have tests.

**Pull request merged**
