### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tuler**
This is a overall update of dependencies of all sub-packages.
After that this is the output of `pnpm -r outdated`

```
┌────────────────────────────┬─────────┬────────────┬───────────────────┐
│ Package                    │ Current │ Latest     │ Dependents        │
├────────────────────────────┼─────────┼────────────┼───────────────────┤
│ @ensdomains/ens (dev)      │ 0.6.2   │ Deprecated │ @sunodo/contracts │
├────────────────────────────┼─────────┼────────────┼───────────────────┤
│ @ensdomains/resolver (dev) │ 0.3.1   │ Deprecated │ @sunodo/contracts │
├────────────────────────────┼─────────┼────────────┼───────────────────┤
│ @inquirer/prompts          │ 3.3.2   │ 4.1.0      │ @sunodo/cli       │
├────────────────────────────┼─────────┼────────────┼───────────────────┤
│ @openzeppelin/contracts    │ 4.9.3   │ 5.0.1      │ @sunodo/contracts │
└────────────────────────────┴─────────┴────────────┴───────────────────┘
```

@ensdomains/ens and @ensdomains/resolver are being used by @ethereum-waffle/ens, which is being used to deploy ENS contracts to devnet. We need to investigate how to do it without using @ethereum-waffle/ens, which is not well maintained.
Posted a message about this at https://github.com/wevm/viem/discussions/1834

@inquirer/prompts has a breaking change, and I posted a message about how to deal with it
https://github.com/SBoudrias/Inquirer.js/discussions/1362

@openzeppelin/contracts is at v4 because Cartesi contracts 1.2 also use v4. It would be confusing to use v5 (requires aliasing).

### CODE REVIEW

**Review by endersonmaia — APPROVED** [review]
Is it worth having individual commits per package?

**Comment by tuler** [comment]
> Is it worth having individual commits per package?

That will be a LOT of work.
I can try if you REALLY think it's important.

Maybe I can do only for those that required code change

**Comment by endersonmaia** [comment]
We had a CI error for the Release workflow, can we fix here?

While you fix the merge conflicts.

**Comment by tuler** [comment]
I'll update this PR to first upgrade `viem` from v1 to v2, which is the one that brings code changes. And another commit to update the rest (non-breaking changes).

**Comment by tuler** [comment]
PR updated with a better commit history.
Final result is:
```
┌───────────────────────────┬─────────┬────────┬───────────────────┐
│ Package                   │ Current │ Latest │ Dependents        │
├───────────────────────────┼─────────┼────────┼───────────────────┤
│ @ensdomains/ens-contracts │ 1.0.0   │ 1.1.4  │ @sunodo/contracts │
├───────────────────────────┼─────────┼────────┼───────────────────┤
│ @inquirer/prompts         │ 3.3.2   │ 4.1.0  │ @sunodo/cli       │
├───────────────────────────┼─────────┼────────┼───────────────────┤
│ @openzeppelin/contracts   │ 4.9.3   │ 5.0.1  │ @sunodo/contracts │
└───────────────────────────┴─────────┴────────┴───────────────────┘
```

I decided to leave `@ensdomains/ens-contracts` in 1.0.0 by now, and change it how dealing with https://github.com/sunodo/sunodo/issues/380

**Comment by endersonmaia** [comment]
There are some linting warning on the lint CI, take a look if they deserve fixing.

**Review by endersonmaia — APPROVED** [review]

**Pull request merged**
