### PR TITLE
Support to base network

### PR DESCRIPTION
**Pull request by tuler**
This completes support to base network.
It adds base to the deploy web app.
It adds base to CLI in wallet selection for sunodo send.
It adds base to documentation.

### CODE REVIEW

**Review by endersonmaia — APPROVED** [review]
Isn´t there a base-sepolia network?

**Comment by tuler** [comment]
> Isn´t there a base-sepolia network?

I wasn't aware until yesterday there is a base-sepolia network.

If we really want to deploy to base-sepolia we need to add it all the way from the `solidity-util` package, to the `rollups-contracts` package to here.

Do you think it's necessary?

**Comment by tuler** [comment]
> Do you think it's necessary?

For consistency it's probably better to do it.

**Comment by tuler** [comment]
But I think we can merge this one, and then add base sepolia

**Pull request merged**
